const API_BASENAME = "http://localhost:8000";
export const API_PATHS = {
    auth: API_BASENAME + "/me",
    refresh: API_BASENAME + "/refresh",
    register: API_BASENAME + "/register",
    login: API_BASENAME + "/login",
    logout: API_BASENAME + "/logout",
    user: API_BASENAME + "/user",
    delete_user: API_BASENAME + "/user",
    reset_password: API_BASENAME + "/todo",

    create_ad: API_BASENAME + "/ads/create",
    get_ads: API_BASENAME + "/ads",
    get_my_ads: API_BASENAME + "/ads/my",
    get_ads_to_check: API_BASENAME + "/todo",
    get_reported_ads: API_BASENAME + "/todo",
    get_ad_creator: API_BASENAME + "/todo",
    remove_ad: API_BASENAME + "/todo",

    change_name: API_BASENAME + "/user/name",
    change_phone: API_BASENAME + "/user/phone",
    change_email: API_BASENAME + "/user/email",
    change_password: API_BASENAME + "/user/password",
    change_vk: API_BASENAME + "/todo",
    change_tg: API_BASENAME + "/todo",
    change_max: API_BASENAME + "/todo",
    change_notifications_location: API_BASENAME + "/todo",

    get_server_stats: API_BASENAME + "/todo",
};

export const DEBUG = true;

export const CREATE_AD_STAGES = [
    "1. Основная информация",
    "2. Информация о животном",
    "3. Место и время",
];

export const AD_INFO_DICT = {
    status: {
        lost: "Потеряно",
        found: "Найдено",
        closed: "Снято",
        any: "Любой",
    },
    type: { dog: "Собака", cat: "Кошка", any: "Любое" },
    breed: {
        labrador: "Лабрадор",
        german_shepherd: "Немецкая овчарка",
        poodle: "Пудель",
        metis: "Метис",
        any: "Любая",
    },
    size: {
        little: "Небольшой",
        medium: "Средний",
        big: "Крупный",
        any: "Любой",
    },
    danger: {
        safe: "Безопасен",
        danger: "Может быть опасен",
        unknown: "Опасен или нет неизвестно",
        any: "Любая",
    },
    region: {
        adygeya: "респ. Адыгея",
        altai: "респ. Алтай",
        altai_krai: "Алтайский край",
        amur: "Амурская обл.",
        arkhangelsk: "Архангельская обл.",
        astrakhan: "Астраханская обл.",
        baikonur: "г. Байконур",
        bashkortostan: "респ. Башкортостан",
        belgorod: "Белгородская обл.",
        bryansk: "Брянская обл.",
        buryatiya: "респ. Бурятия",
        vladimir: "Владимирская обл.",
        volgograd: "Волгоградская обл.",
        vologda: "Вологодская обл.",
        voronezh: "Воронежская обл.",
        dagestan: "респ. Дагестан",
        jewish_autonomous_oblast: "Еврейская авт. обл.",
        zabaykalsky: "Забайкальский край",
        ivanovo: "Ивановская обл.",
        ingushetiya: "респ. Ингушетия",
        irkutsk: "Иркутская обл.",
        kabardino_balkaria: "респ. Кабардино-Балкария",
        kaliningrad: "Калининградская обл.",
        kalmykiya: "респ. Калмыкия",
        kaluga: "Калужская обл.",
        kamchatka: "Камчатский край",
        karachay_cherkessia: "респ. Карачаево-Черкесия",
        kareliya: "респ. Карелия",
        kemerovo: "Кемеровская обл.",
        kirov: "Кировская обл.",
        komi: "респ. Коми",
        kostroma: "Костромская обл.",
        krasnodar: "Краснодарский край",
        krasnoyarsk: "Красноярский край",
        kurgan: "Курганская обл.",
        kursk: "Курская обл.",
        leningrad: "Ленинградская обл.",
        lipetsk: "Липецкая обл.",
        magadan: "Магаданская обл.",
        mariy_el: "респ. Марий Эл",
        moscow: "Московская обл.",
        moscow_city: "г. Москва",
        murmansk: "Мурманская обл.",
        mordoviya: "респ. Мордовия",
        nenets: "Ненецкий авт. округ",
        nizhny_novgorod: "Нижегородская обл.",
        novgorod: "Новгородская обл.",
        novosibirsk: "Новосибирская обл.",
        omsk: "Омская обл.",
        orenburg: "Оренбургская обл.",
        oryol: "Орловская обл.",
        penza: "Пензенская обл.",
        perm: "Пермский край",
        primorsky: "Приморский край",
        pskov: "Псковская обл.",
        rostov: "Ростовская обл.",
        ryazan: "Рязанская обл.",
        samara: "Самарская обл.",
        saratov: "Саратовская обл.",
        sakha: "респ. Якутия",
        sakhalin: "Сахалинская обл.",
        sevastopol_city: "г. Севастополь",
        north_ossetia: "респ. Северная Осетия",
        smolensk: "Смоленская обл.",
        st_petersburg_city: "г. Санкт-Петербург",
        stavropol: "Ставропольский край",
        sverdlovsk: "Свердловская обл.",
        tambov: "Тамбовская обл.",
        tatarstan: "респ. Татарстан",
        tomsk: "Томская обл.",
        tula: "Тульская обл.",
        tver: "Тверская обл.",
        tyumen: "Тюменская обл.",
        tyva: "респ. Тыва",
        udmurtiya: "респ. Удмуртия",
        ulyanovsk: "Ульяновская обл.",
        khabarovsk: "Хабаровский край",
        khakasiya: "респ. Хакасия",
        khanty_mansi: "Ханты-Мансийский авт. округ",
        chelyabinsk: "Челябинская обл.",
        chechen: "респ. Чечня",
        chuvashiya: "респ. Чувашия",
        chukotka: "Чукотский авт. округ",
        yamalo_nenets: "Ямало-Ненецкий авт. округ",
        yaroslavl: "Ярославская обл."
    }
};

export const AD_FILTERS_DICT = {
    status: "Статус",
    type: "Животное",
    breed: "Порода",
    size: "Размер",
    danger: "Опасность",
    region: "Регион",
    geoloc: "Геолокация",
    radius: "Радиус поиска",
};

export const DROPDOWN_CHOICES = {
    status: [
        ["lost", "Потеряли"],
        ["found", "Нашли"],
    ],
    type: [
        ["dog", "Собака"],
        ["cat", "Кошка"],
    ],
    breed: [
        ["labrador", "Лабрадор"],
        ["german_shepherd", "Немецкая овчарка"],
        ["poodle", "Пудель"],
        ["metis", "Метис"],
    ],
    size: [
        ["little", "Маленький"],
        ["medium", "Средний"],
        ["big", "Крупный"],
    ],
    danger: [
        ["danger", "Да"],
        ["safe", "Нет"],
        ["unknown", "Не знаю"],
    ],
    region: [
        ["adygeya", "респ. Адыгея"],
        ["altai", "респ. Алтай"],
        ["altai_krai", "Алтайский край"],
        ["amur", "Амурская обл."],
        ["arkhangelsk", "Архангельская обл."],
        ["astrakhan", "Астраханская обл."],
        ["baikonur", "г. Байконур"],
        ["bashkortostan", "респ. Башкортостан"],
        ["belgorod", "Белгородская обл."],
        ["bryansk", "Брянская обл."],
        ["buryatiya", "респ. Бурятия"],
        ["vladimir", "Владимирская обл."],
        ["volgograd", "Волгоградская обл."],
        ["vologda", "Вологодская обл."],
        ["voronezh", "Воронежская обл."],
        ["dagestan", "респ. Дагестан"],
        ["jewish_autonomous_oblast", "Еврейская авт. обл."],
        ["zabaykalsky", "Забайкальский край"],
        ["ivanovo", "Ивановская обл."],
        ["ingushetiya", "респ. Ингушетия"],
        ["irkutsk", "Иркутская обл."],
        ["kabardino_balkaria", "респ. Кабардино-Балкария"],
        ["kaliningrad", "Калининградская обл."],
        ["kalmykiya", "респ. Калмыкия"],
        ["kaluga", "Калужская обл."],
        ["kamchatka", "Камчатский край"],
        ["karachay_cherkessia", "респ. Карачаево-Черкесия"],
        ["kareliya", "респ. Карелия"],
        ["kemerovo", "Кемеровская обл."],
        ["kirov", "Кировская обл."],
        ["komi", "респ. Коми"],
        ["kostroma", "Костромская обл."],
        ["krasnodar", "Краснодарский край"],
        ["krasnoyarsk", "Красноярский край"],
        ["kurgan", "Курганская обл."],
        ["kursk", "Курская обл."],
        ["leningrad", "Ленинградская обл."],
        ["lipetsk", "Липецкая обл."],
        ["magadan", "Магаданская обл."],
        ["mariy_el", "респ. Марий Эл"],
        ["moscow", "Московская обл."],
        ["moscow_city", "г. Москва"],
        ["murmansk", "Мурманская обл."],
        ["mordoviya", "респ. Мордовия"],
        ["nenets", "Ненецкий авт. округ"],
        ["nizhny_novgorod", "Нижегородская обл."],
        ["novgorod", "Новгородская обл."],
        ["novosibirsk", "Новосибирская обл."],
        ["omsk", "Омская обл."],
        ["orenburg", "Оренбургская обл."],
        ["oryol", "Орловская обл."],
        ["penza", "Пензенская обл."],
        ["perm", "Пермский край"],
        ["primorsky", "Приморский край"],
        ["pskov", "Псковская обл."],
        ["rostov", "Ростовская обл."],
        ["ryazan", "Рязанская обл."],
        ["samara", "Самарская обл."],
        ["saratov", "Саратовская обл."],
        ["sakha", "респ. Якутия"],
        ["sakhalin", "Сахалинская обл."],
        ["sevastopol_city", "г. Севастополь"],
        ["north_ossetia", "респ. Северная Осетия"],
        ["smolensk", "Смоленская обл."],
        ["st_petersburg_city", "г. Санкт-Петербург"],
        ["stavropol", "Ставропольский край"],
        ["sverdlovsk", "Свердловская обл."],
        ["tambov", "Тамбовская обл."],
        ["tatarstan", "респ. Татарстан"],
        ["tomsk", "Томская обл."],
        ["tula", "Тульская обл."],
        ["tver", "Тверская обл."],
        ["tyumen", "Тюменская обл."],
        ["tyva", "респ. Тыва"],
        ["udmurtiya", "респ. Удмуртия"],
        ["ulyanovsk", "Ульяновская обл."],
        ["khabarovsk", "Хабаровский край"],
        ["khakasiya", "респ. Хакасия"],
        ["khanty_mansi", "Ханты-Мансийский авт. округ"],
        ["chelyabinsk", "Челябинская обл."],
        ["chechen", "респ. Чечня"],
        ["chuvashiya", "респ. Чувашия"],
        ["chukotka", "Чукотский авт. округ"],
        ["yamalo_nenets", "Ямало-Ненецкий авт. округ"],
        ["yaroslavl", "Ярославская обл."]
    ]
};
