const API_BASENAME = "http://localhost:8000";
export const API_PATHS = {
    auth: API_BASENAME + "/me",
    refresh: API_BASENAME + "/refresh",
    register: API_BASENAME + "/register",
    login: API_BASENAME + "/login",
    logout: API_BASENAME + "/logout",
    user: API_BASENAME + "/user",
    delete_user: API_BASENAME + "/user",
    reset_password: API_BASENAME + "/user/password/reset",

    create_ad: API_BASENAME + "/ads/create",
    get_ads: API_BASENAME + "/ads",
    get_user_ads: API_BASENAME + "/ads/user",
    get_ads_to_check: API_BASENAME + "/ads/to_check",
    get_reported_ads: API_BASENAME + "/ads/reported",
    get_ad_and_creator: API_BASENAME + "/ad/data",
    close_ad: API_BASENAME + "/ad/remove",
    delete_ad: API_BASENAME + "/ad/delete",
    approve_ad: API_BASENAME + "/ad/approve",

    change_avatar: API_BASENAME + "/user/avatar",
    change_name: API_BASENAME + "/user/name",
    change_phone: API_BASENAME + "/user/phone",
    change_email: API_BASENAME + "/user/email",
    change_password: API_BASENAME + "/user/password",
    change_vk: API_BASENAME + "/user/vk",
    change_tg: API_BASENAME + "/user/tg",
    change_max: API_BASENAME + "/user/max",
    change_notifications_location: API_BASENAME + "/user/location",

    get_server_stats: API_BASENAME + "/todo",
};

export const DEBUG = true;

export const CREATE_AD_STAGES = [
    "1. Основная информация",
    "2. Информация о животном",
    "3. Место и время",
];

export const AD_INFO_DICT = {
    status: {
        lost: "Потеряно",
        found: "Найдено",
        closed: "Снято",
        any: "Любой",
    },
    type: { dog: "Собака", cat: "Кошка", any: "Любое" },
    breed: {
        labrador: "Лабрадор-ретривер",
        german_shepherd: "Немецкая овчарка",
        golden_retriever: "Золотистый ретривер",
        french_bulldog: "Французский бульдог",
        beagle: "Бигль",
        poodle: "Пудель",
        bulldog: "Английский бульдог",
        rottweiler: "Ротвейлер",
        yorkshire_terrier: "Йоркширский терьер",
        boxer: "Боксер",
        siberian_husky: "Сибирский хаски",
        dachshund: "Такса",
        doberman: "Доберман",
        great_dane: "Немецкий дог",
        australian_shepherd: "Австралийская овчарка",
        cavalier_king_charles: "Кавалер кинг чарльз спаниель",
        shih_tzu: "Ши-тцу",
        pomeranian: "Померанский шпиц",
        border_collie: "Бордер-колли",
        chihuahua: "Чихуахуа",
        corgi: "Вельш-корги",
        maltese: "Мальтийская болонка",
        bernese_mountain: "Бернский зенненхунд",
        basset_hound: "Бассет-хаунд",
        mastiff: "Английский мастиф",
        shetland_sheepdog: "Шетландская овчарка",
        staffordshire_bull_terrier: "Стаффордширский бультерьер",
        akita: "Акита-ину",
        shar_pei: "Шарпей",
        weimaraner: "Веймаранер",
        dalmatian: "Далматин",
        jack_russell: "Джек-рассел-терьер",
        papillon: "Папильон",
        samoyed: "Самоед",
        whippet: "Уиппет",
        newfoundland: "Ньюфаундленд",
        bichon_frise: "Бишон фризе",
        bloodhound: "Бладхаунд",
        bull_terrier: "Бультерьер",
        chow_chow: "Чау-чау",
        cocker_spaniel: "Американский кокер-спаниель",
        collie: "Колли",
        english_setter: "Английский сеттер",
        irish_setter: "Ирландский сеттер",
        italian_greyhound: "Итальянская борзая",
        lhasa_apso: "Лхаса апсо",
        miniature_pinscher: "Цвергпинчер",
        old_english_sheepdog: "Бобтейл",
        pekingese: "Пекинес",
        pit_bull: "Питбуль",
        portuguese_water_dog: "Португальская водяная собака",
        pug: "Мопс",
        saint_bernard: "Сенбернар",
        schnauzer: "Цвергшнауцер",
        scottish_terrier: "Скотч-терьер",
        shiba_inu: "Сиба-ину",
        tibetan_mastiff: "Тибетский мастиф",
        west_highland: "Вест-хайленд-уайт-терьер",
        alaskan_malamute: "Аляскинский маламут",

        persian: "Персидская кошка",
        maine_coon: "Мейн-кун",
        siamese: "Сиамская кошка",
        ragdoll: "Рэгдолл",
        bengal: "Бенгальская кошка",
        sphynx: "Сфинкс",
        british_shorthair: "Британская короткошерстная",
        scottish_fold: "Шотландская вислоухая",
        russian_blue: "Русская голубая",
        norwegian_forest: "Норвежская лесная",
        american_shorthair: "Американская короткошерстная",
        exotic_shorthair: "Экзотическая короткошерстная",
        devon_rex: "Девон-рекс",
        abyssinian: "Абиссинская кошка",
        birman: "Бирманская кошка",
        oriental: "Ориентальная кошка",
        cornish_rex: "Корниш-рекс",
        turkish_angora: "Турецкая ангора",
        burmese: "Бурманская кошка",
        tonkinese: "Тонкинская кошка",
        egyptian_mau: "Египетская мау",
        manx: "Мэнская кошка",
        himalayan: "Гималайская кошка",
        somali: "Сомалийская кошка",
        ocicat: "Оцикет",
        chartreux: "Шартрез",
        bombay: "Бомбейская кошка",
        peterbald: "Петерболд",
        savannah: "Саванна",
        toyger: "Тойгер",
        selkirk_rex: "Селкирк-рекс",
        laperm: "Лаперм",
        american_bobtail: "Американский бобтейл",
        japanese_bobtail: "Японский бобтейл",
        kurilian_bobtail: "Курильский бобтейл",
        nebelung: "Нибелунг",
        ragamuffin: "Рагамаффин",
        singapura: "Сингапурская кошка",
        snowshoe: "Сноу-шу",
        turkish_van: "Турецкий ван",
        any: "Любая",
    },
    size: {
        little: "Небольшой",
        medium: "Средний",
        big: "Крупный",
        any: "Любой",
    },
    danger: {
        safe: "Безопасен",
        danger: "Может быть опасен",
        unknown: "Опасен или нет неизвестно",
        any: "Любая",
    },
    region: {
        adygeya: "респ. Адыгея",
        altai: "респ. Алтай",
        altai_krai: "Алтайский край",
        amur: "Амурская обл.",
        arkhangelsk: "Архангельская обл.",
        astrakhan: "Астраханская обл.",
        baikonur: "г. Байконур",
        bashkortostan: "респ. Башкортостан",
        belgorod: "Белгородская обл.",
        bryansk: "Брянская обл.",
        buryatiya: "респ. Бурятия",
        vladimir: "Владимирская обл.",
        volgograd: "Волгоградская обл.",
        vologda: "Вологодская обл.",
        voronezh: "Воронежская обл.",
        dagestan: "респ. Дагестан",
        jewish_autonomous_oblast: "Еврейская авт. обл.",
        zabaykalsky: "Забайкальский край",
        ivanovo: "Ивановская обл.",
        ingushetiya: "респ. Ингушетия",
        irkutsk: "Иркутская обл.",
        kabardino_balkaria: "респ. Кабардино-Балкария",
        kaliningrad: "Калининградская обл.",
        kalmykiya: "респ. Калмыкия",
        kaluga: "Калужская обл.",
        kamchatka: "Камчатский край",
        karachay_cherkessia: "респ. Карачаево-Черкесия",
        kareliya: "респ. Карелия",
        kemerovo: "Кемеровская обл.",
        kirov: "Кировская обл.",
        komi: "респ. Коми",
        kostroma: "Костромская обл.",
        krasnodar: "Краснодарский край",
        krasnoyarsk: "Красноярский край",
        kurgan: "Курганская обл.",
        kursk: "Курская обл.",
        leningrad: "Ленинградская обл.",
        lipetsk: "Липецкая обл.",
        magadan: "Магаданская обл.",
        mariy_el: "респ. Марий Эл",
        moscow: "Московская обл.",
        moscow_city: "г. Москва",
        murmansk: "Мурманская обл.",
        mordoviya: "респ. Мордовия",
        nenets: "Ненецкий авт. округ",
        nizhny_novgorod: "Нижегородская обл.",
        novgorod: "Новгородская обл.",
        novosibirsk: "Новосибирская обл.",
        omsk: "Омская обл.",
        orenburg: "Оренбургская обл.",
        oryol: "Орловская обл.",
        penza: "Пензенская обл.",
        perm: "Пермский край",
        primorsky: "Приморский край",
        pskov: "Псковская обл.",
        rostov: "Ростовская обл.",
        ryazan: "Рязанская обл.",
        samara: "Самарская обл.",
        saratov: "Саратовская обл.",
        sakha: "респ. Якутия",
        sakhalin: "Сахалинская обл.",
        sevastopol_city: "г. Севастополь",
        north_ossetia: "респ. Северная Осетия",
        smolensk: "Смоленская обл.",
        st_petersburg_city: "г. Санкт-Петербург",
        stavropol: "Ставропольский край",
        sverdlovsk: "Свердловская обл.",
        tambov: "Тамбовская обл.",
        tatarstan: "респ. Татарстан",
        tomsk: "Томская обл.",
        tula: "Тульская обл.",
        tver: "Тверская обл.",
        tyumen: "Тюменская обл.",
        tyva: "респ. Тыва",
        udmurtiya: "респ. Удмуртия",
        ulyanovsk: "Ульяновская обл.",
        khabarovsk: "Хабаровский край",
        khakasiya: "респ. Хакасия",
        khanty_mansi: "Ханты-Мансийский авт. округ",
        chelyabinsk: "Челябинская обл.",
        chechen: "респ. Чечня",
        chuvashiya: "респ. Чувашия",
        chukotka: "Чукотский авт. округ",
        yamalo_nenets: "Ямало-Ненецкий авт. округ",
        yaroslavl: "Ярославская обл.",
        any: "Любой",
    },
};

export const AD_FILTERS_DICT = {
    status: "Статус",
    type: "Животное",
    breed: "Порода",
    size: "Размер",
    danger: "Опасность",
    region: "Регион",
    geoloc: "Геолокация",
    radius: "Радиус поиска",
};

export const DROPDOWN_CHOICES = {
    status: [
        ["lost", "Потеряли"],
        ["found", "Нашли"],
    ],
    type: [
        ["dog", "Собака"],
        ["cat", "Кошка"],
    ],
    breed: [
        ["labrador", "Лабрадор-ретривер"],
        ["german_shepherd", "Немецкая овчарка"],
        ["golden_retriever", "Золотистый ретривер"],
        ["french_bulldog", "Французский бульдог"],
        ["beagle", "Бигль"],
        ["poodle", "Пудель"],
        ["bulldog", "Английский бульдог"],
        ["rottweiler", "Ротвейлер"],
        ["yorkshire_terrier", "Йоркширский терьер"],
        ["boxer", "Боксер"],
        ["siberian_husky", "Сибирский хаски"],
        ["dachshund", "Такса"],
        ["doberman", "Доберман"],
        ["great_dane", "Немецкий дог"],
        ["australian_shepherd", "Австралийская овчарка"],
        ["cavalier_king_charles", "Кавалер кинг чарльз спаниель"],
        ["shih_tzu", "Ши-тцу"],
        ["pomeranian", "Померанский шпиц"],
        ["border_collie", "Бордер-колли"],
        ["chihuahua", "Чихуахуа"],
        ["corgi", "Вельш-корги"],
        ["maltese", "Мальтийская болонка"],
        ["bernese_mountain", "Бернский зенненхунд"],
        ["basset_hound", "Бассет-хаунд"],
        ["mastiff", "Английский мастиф"],
        ["shetland_sheepdog", "Шетландская овчарка"],
        ["staffordshire_bull_terrier", "Стаффордширский бультерьер"],
        ["akita", "Акита-ину"],
        ["shar_pei", "Шарпей"],
        ["weimaraner", "Веймаранер"],
        ["dalmatian", "Далматин"],
        ["jack_russell", "Джек-рассел-терьер"],
        ["papillon", "Папильон"],
        ["samoyed", "Самоед"],
        ["whippet", "Уиппет"],
        ["newfoundland", "Ньюфаундленд"],
        ["bichon_frise", "Бишон фризе"],
        ["bloodhound", "Бладхаунд"],
        ["bull_terrier", "Бультерьер"],
        ["chow_chow", "Чау-чау"],
        ["cocker_spaniel", "Американский кокер-спаниель"],
        ["collie", "Колли"],
        ["english_setter", "Английский сеттер"],
        ["irish_setter", "Ирландский сеттер"],
        ["italian_greyhound", "Итальянская борзая"],
        ["lhasa_apso", "Лхаса апсо"],
        ["miniature_pinscher", "Цвергпинчер"],
        ["old_english_sheepdog", "Бобтейл"],
        ["pekingese", "Пекинес"],
        ["pit_bull", "Питбуль"],
        ["portuguese_water_dog", "Португальская водяная собака"],
        ["pug", "Мопс"],
        ["saint_bernard", "Сенбернар"],
        ["schnauzer", "Цвергшнауцер"],
        ["scottish_terrier", "Скотч-терrier"],
        ["shiba_inu", "Сиба-ину"],
        ["tibetan_mastiff", "Тибетский мастиф"],
        ["west_highland", "Вест-хайленд-уайт-терьер"],
        ["alaskan_malamute", "Аляскинский маламут"],

        ["persian", "Персидская кошка"],
        ["maine_coon", "Мейн-кун"],
        ["siamese", "Сиамская кошка"],
        ["ragdoll", "Рэгдолл"],
        ["bengal", "Бенгальская кошка"],
        ["sphynx", "Сфинкс"],
        ["british_shorthair", "Британская короткошерстная"],
        ["scottish_fold", "Шотландская вислоухая"],
        ["russian_blue", "Русская голубая"],
        ["norwegian_forest", "Норвежская лесная"],
        ["american_shorthair", "Американская короткошерстная"],
        ["exotic_shorthair", "Экзотическая короткошерстная"],
        ["devon_rex", "Девон-рекс"],
        ["abyssinian", "Абиссинская кошка"],
        ["birman", "Бирманская кошка"],
        ["oriental", "Ориентальная кошка"],
        ["cornish_rex", "Корниш-рекс"],
        ["turkish_angora", "Турецкая ангора"],
        ["burmese", "Бурманская кошка"],
        ["tonkinese", "Тонкинская кошка"],
        ["egyptian_mau", "Египетская мау"],
        ["manx", "Мэнская кошка"],
        ["himalayan", "Гималайская кошка"],
        ["somali", "Сомалийская кошка"],
        ["ocicat", "Оцикет"],
        ["chartreux", "Шартрез"],
        ["bombay", "Бомбейская кошка"],
        ["peterbald", "Петерболд"],
        ["savannah", "Саванна"],
        ["toyger", "Тойгер"],
        ["selkirk_rex", "Селкирк-рекс"],
        ["laperm", "Лаперм"],
        ["american_bobtail", "Американский бобтейл"],
        ["japanese_bobtail", "Японский бобтейл"],
        ["kurilian_bobtail", "Курильский бобтейл"],
        ["nebelung", "Нибелунг"],
        ["ragamuffin", "Рагамаффин"],
        ["singapura", "Сингапурская кошка"],
        ["snowshoe", "Сноу-шу"],
        ["turkish_van", "Турецкий ван"],
    ],
    size: [
        ["little", "Маленький"],
        ["medium", "Средний"],
        ["big", "Крупный"],
    ],
    danger: [
        ["danger", "Да"],
        ["safe", "Нет"],
        ["unknown", "Не знаю"],
    ],
    region: [
        ["adygeya", "респ. Адыгея"],
        ["altai", "респ. Алтай"],
        ["altai_krai", "Алтайский край"],
        ["amur", "Амурская обл."],
        ["arkhangelsk", "Архангельская обл."],
        ["astrakhan", "Астраханская обл."],
        ["baikonur", "г. Байконур"],
        ["bashkortostan", "респ. Башкортостан"],
        ["belgorod", "Белгородская обл."],
        ["bryansk", "Брянская обл."],
        ["buryatiya", "респ. Бурятия"],
        ["vladimir", "Владимирская обл."],
        ["volgograd", "Волгоградская обл."],
        ["vologda", "Вологодская обл."],
        ["voronezh", "Воронежская обл."],
        ["dagestan", "респ. Дагестан"],
        ["jewish_autonomous_oblast", "Еврейская авт. обл."],
        ["zabaykalsky", "Забайкальский край"],
        ["ivanovo", "Ивановская обл."],
        ["ingushetiya", "респ. Ингушетия"],
        ["irkutsk", "Иркутская обл."],
        ["kabardino_balkaria", "респ. Кабардино-Балкария"],
        ["kaliningrad", "Калининградская обл."],
        ["kalmykiya", "респ. Калмыкия"],
        ["kaluga", "Калужская обл."],
        ["kamchatka", "Камчатский край"],
        ["karachay_cherkessia", "респ. Карачаево-Черкесия"],
        ["kareliya", "респ. Карелия"],
        ["kemerovo", "Кемеровская обл."],
        ["kirov", "Кировская обл."],
        ["komi", "респ. Коми"],
        ["kostroma", "Костромская обл."],
        ["krasnodar", "Краснодарский край"],
        ["krasnoyarsk", "Красноярский край"],
        ["kurgan", "Курганская обл."],
        ["kursk", "Курская обл."],
        ["leningrad", "Ленинградская обл."],
        ["lipetsk", "Липецкая обл."],
        ["magadan", "Магаданская обл."],
        ["mariy_el", "респ. Марий Эл"],
        ["moscow", "Московская обл."],
        ["moscow_city", "г. Москва"],
        ["murmansk", "Мурманская обл."],
        ["mordoviya", "респ. Мордовия"],
        ["nenets", "Ненецкий авт. округ"],
        ["nizhny_novgorod", "Нижегородская обл."],
        ["novgorod", "Новгородская обл."],
        ["novosibirsk", "Новосибирская обл."],
        ["omsk", "Омская обл."],
        ["orenburg", "Оренбургская обл."],
        ["oryol", "Орловская обл."],
        ["penza", "Пензенская обл."],
        ["perm", "Пермский край"],
        ["primorsky", "Приморский край"],
        ["pskov", "Псковская обл."],
        ["rostov", "Ростовская обл."],
        ["ryazan", "Рязанская обл."],
        ["samara", "Самарская обл."],
        ["saratov", "Саратовская обл."],
        ["sakha", "респ. Якутия"],
        ["sakhalin", "Сахалинская обл."],
        ["sevastopol_city", "г. Севастополь"],
        ["north_ossetia", "респ. Северная Осетия"],
        ["smolensk", "Смоленская обл."],
        ["st_petersburg_city", "г. Санкт-Петербург"],
        ["stavropol", "Ставропольский край"],
        ["sverdlovsk", "Свердловская обл."],
        ["tambov", "Тамбовская обл."],
        ["tatarstan", "респ. Татарстан"],
        ["tomsk", "Томская обл."],
        ["tula", "Тульская обл."],
        ["tver", "Тверская обл."],
        ["tyumen", "Тюменская обл."],
        ["tyva", "респ. Тыва"],
        ["udmurtiya", "респ. Удмуртия"],
        ["ulyanovsk", "Ульяновская обл."],
        ["khabarovsk", "Хабаровский край"],
        ["khakasiya", "респ. Хакасия"],
        ["khanty_mansi", "Ханты-Мансийский авт. округ"],
        ["chelyabinsk", "Челябинская обл."],
        ["chechen", "респ. Чечня"],
        ["chuvashiya", "респ. Чувашия"],
        ["chukotka", "Чукотский авт. округ"],
        ["yamalo_nenets", "Ямало-Ненецкий авт. округ"],
        ["yaroslavl", "Ярославская обл."],
    ],
};

export const AUTHORS = [
    { title: "shuler07", description: "Frontend / UI", img: "/images/shuler07.webp" },
    { title: "iszenzi", description: "Backend", img: "/images/iszenzi.webp" },
    { title: "chubinho", description: "Backend", img: "/images/chubinho.webp" },
    { title: "maxat228", description: "Teamlead", img: "/images/maxat228.webp" },
    { title: "dubchakm97-lgtm", description: "Design", img: "/images/dubchakm97-lgtm.webp" },
];
